# 应用服务 WEB 访问端口
server:
  port: 8789

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/binaryTea
#spring.datasource.username=root
#spring.datasource.password=lalala123
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/binaryTea?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#      username: root
#      password: lalala123
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        login-username: admin
#        login-password: admin
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/binaryTea?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: lalala123
  jpa:
    hibernate:
      ddl-auto: update

